Iter13
1Asi1/metric-track pull request #13
Opened 2023-12-14 10:44 UTC by 1Asi1

2023-12-14 22:48 UTC, s-shpak requested changes
Я обратил внимание, что ты не скопирвал файл конфигурации линтера в репозиторий. Так и задумывалось? Потому что сейчас отсутствует довольно большое количество полезных проверок. Если буедшь его добавлять, то скопируй https://github.com/s-shpak/praktikum-golangci-lint/blob/main/.golangci.yml в корень проекта

2023-12-14 22:48 UTC, s-shpak commented on cmd/server/main.go
> +		log.Println("godotenv.Load error")
Я бы выходил из программы здесь: если какой-то способ прочитать конфигурацию не срабатывает, то опасно продолжать выполнение, т.к. пользователь может не заметить это, а при этом отсутствие каких-то параметров или их неверное выставление может сильно повлиять на работу приложения

2023-12-14 22:48 UTC, s-shpak commented on internal/agent/integration/metric.go
> +	defer func() { err = gz.Close() }()
Ты никак не обрабатываешь эту ошибку. Либо игнорируй ее через `_`, либо логируй. Кроме того повторный вызов `Close` после строки 181, насколько я помню, будет приводить к ошибке. Подумай, как это лучше решить

2023-12-14 22:48 UTC, s-shpak commented on internal/agent/integration/metric.go
> +	defer func() { err = res.RawBody().Close() }()
См. выше

2023-12-14 22:48 UTC, s-shpak commented on internal/server/config/config.go
> +	postgresql := flag.String("d", NullPostgreURL, "url connecting to postgres")
1. Это не URL, это dsn
2. Почему бы просто не оставлять ее пустой ? Пустое значение тоже подразумевает использование другого типа хранилища

2023-12-14 22:48 UTC, s-shpak commented on internal/server/config/config.go
> +		l.Info().Msgf("postgresql address value: %s", postgresqlAddrEnv)
Не надо это логировать, там может быть конфиденциальная информация (и скорее всего будет)

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +	return errors.New("db not included")
Поделись, пожалуйста, почему ты решил, что возвращать ошибку здесь хорошая идея ? Я не в первой работе это вижу, мне интересно.

Кажется, что для `memory store` это просто `nop`-операция (извини за тавтологию)

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/migrations/000001_create_metrics_table.up.sql
> +       gauge double precision,
Я советую явным образом помечать nullable аттрибуты как `NULL`

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +type Postgres struct {
Не стоит оставлять конкретное именование БД в коде, если мы ее поменяем, имена также придется менять

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +	sync.RWMutex
Мьютексы лучше хранить как указатели, т.к. их нельзя копировать

Кроме того здесь мьютекс нельзя встраивать, т.к. это выставляет его публичные метоы вовне (то есть пользователь `Postgres` может вызвать лок)

Кроме того мьютекс тебе просто не нужен

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +			pgErrCode := (err).(pgx.PgError).Code
Что если не получится скастовать err в `PgError`?

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +			if pgErrCode == pgerrcode.InvalidAuthorizationSpecification {
Что если это `false`?

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +	*sqlx.DB
Аналогично, я бы не стал встраивать - в данной ситуации лучше точно управлять тем, какие именно методы экспортируются

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +	for i := 1; ; i += 2 {
Это никак не конифгурируемо ? Можно хотя бы вынести количество повторов в константу на уровне пакета.

Почему, кстати, прибавляется сразу `2` ?

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +		ticker := time.NewTicker(time.Duration(i) * time.Second)
Это никак не конфигурируемо?

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +	p.Lock()
Здесь не надо вызывать Lock. Мне кажется, ты путаешь мьютексы и транзакции ?

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +	if reflect.DeepEqual(chek, memory.Type{}) {
Не надо пользоваться рефлексией, это дорого

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +			l.Err(err).Msg("p.db.NamedExecContext")
Можем ли мы продолжить выполнение после этой ошибки?

2023-12-14 22:48 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +		INSERT INTO tbl_metrics(id,gauge,counter)
Тебе не обязательно делать запрос к БД до этого, а потом объявлять ветвление. Твой код можно сделать более лаконичным, используя `INSERT...ON CONFLICT`

2023-12-14 22:48 UTC, s-shpak commented on internal/server/transport/rest/v1/metric.go
> +		l.Error().Err(err).Msgf("json.Unmarshal, request value: %+v", r)
Штатные ошибки не стоит логировать - они только забивают логи

2023-12-18 07:55 UTC, 1Asi1 commented on internal/server/repository/postgres/postgres.go
> +		ticker := time.NewTicker(time.Duration(i) * time.Second)
в дз написано 1,3,5 сек

2023-12-18 08:14 UTC, 1Asi1 commented on internal/agent/integration/metric.go
> +	defer func() { err = gz.Close() }()
убирал повторный Close, получил ошибку при отправке,вернул-заработало

2023-12-18 09:06 UTC, 1Asi1 commented
"Я обратил внимание, что ты не скопирвал файл конфигурации линтера в репозиторий. Так и задумывалось? Потому что сейчас отсутствует довольно большое количество полезных проверок. Если буедшь его добавлять, то скопируй https://github.com/s-shpak/praktikum-golangci-lint/blob/main/.golangci.yml в корень проекта" Он лежит в корне, просто под gitignore

2023-12-18 09:30 UTC, 1Asi1 commented on cmd/server/main.go
> +		log.Println("godotenv.Load error")
удалил, ибо в первых итерациях автотеста фаталит приложение не запустив его, для локального запуска только делал

2023-12-18 23:22 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +	return errors.New("db not included")
Ты не мог бы пояснить это, пожалуйста? Почему ты изначально решил возвращать ошибку ? Может быть это было в каком-то примере, или во внешней статье или т.п. Мне хотелось бы это узнать, чтобы в дальнейшем этой ошибки можно было бы избегать. Заранее спасибо!

2023-12-18 23:35 UTC, s-shpak requested changes
`.golangci.yml` стоит пушить в репозиторий, т.к. это позволяет Github Actions запускать линтер с твоими настройками

2023-12-18 23:35 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +			pgErrCode := (err).(pgx.PgError).Code
Это не решено

2023-12-18 23:35 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +			if pgErrCode == pgerrcode.InvalidAuthorizationSpecification {
Это не решено

2023-12-18 23:35 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
Если мы переименовали структуры, то файл и директорию также можн переименовать

2023-12-18 23:35 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +	storage
Ты не мог бы пояснить, зачем ты решил встроить интерфейс в структуру ? Кажется, что это не имеет смысла делать, учитывая, что интерфейс неэкспортируем

2023-12-18 23:35 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +	SelectContext(ctx context.Context, dest interface{}, query string, args ...interface{}) error
Кажется, что не стоит давать методу суффикс "Context" - интерфейс, в любом случае, не предоставляет метода без использования контекста

2023-12-18 23:35 UTC, s-shpak commented on internal/server/repository/postgres/postgres.go
> +		result, err := s.NamedExecContext(context.Background(), query, model)
Почеиу ты не используешь здесь полученный первым аргументом контекст?

2023-12-18 23:35 UTC, s-shpak commented on internal/server/service/metric.go
> +	ctx = context.WithValue(ctx, nameID, req.ID)
Как мы обсудили на вебинаре сегодня, нет смысла передавать значения через контекст

2023-12-19 07:36 UTC, 1Asi1 commented on internal/server/repository/memory/store.go
> +	return errors.New("db not included")
просто если не подключено база уведомлять клиент что не все опции и ручки работают

2023-12-19 07:37 UTC, 1Asi1 commented on internal/server/repository/postgres/postgres.go
> +			pgErrCode := (err).(pgx.PgError).Code
`if _, ok := (err).(pgx.PgError); !ok {
				return &Store{}, fmt.Errorf("postgres connection error: %w", err)
			}`
этой строчкой вроде решено или нет?

2023-12-19 07:38 UTC, 1Asi1 commented on internal/server/repository/postgres/postgres.go
> +			if pgErrCode == pgerrcode.InvalidAuthorizationSpecification {
если false то блок с if не сработает и `return &Store{}, fmt.Errorf("postgres connection error: %w", err)`

2023-12-19 08:23 UTC, 1Asi1 commented
я добавил линтер с игнора, только не совсем понимаю зачем исправлять все. Например рекомендация линтера по уменьшению веса в памяти у структуры: "Error: fieldalignment: struct with 48 pointer bytes could be 40". К тому же этот линтер вродь не поддерживатеся больше комьюнити, хоть моментами и полезная.

2023-12-20 00:05 UTC, s-shpak requested changes
Конфигурация линтера, которую ты добавил, кажется мне достаточно универсальной. Тем не менее, если тебе не хочется использовать некоторые линтеры из нее (или вообще не хочется использовать линтер) ты можешь: 1. убрать из конфигурации линтеры, которые тебя не устраивают: для этого удали линтер из списка `linters.enable` 2. вообще отключить линтинг: не рекомендую это делать, но это не запрещено. Для этого удали `.github/workflows/golangci-lint.yml`

Если хочешь, то можем обсудить полезность или бесполезность некоторых линтеров

2023-12-20 00:05 UTC, s-shpak commented on internal/server/repository/storage/storage.go
> +			pgErrCode := (err).(pgx.PgError).Code
На 61 строчке ты уже привел тип ошибки к `pgx.PgError`, переиспользуй полученное значение

2023-12-20 11:39 UTC, s-shpak approved these changes

2023-12-20 12:34 UTC, merged