Iter15
1Asi1/metric-track pull request #15
Opened 2023-12-28 10:22 UTC by 1Asi1

2023-12-29 08:31 UTC, s-shpak requested changes
Агент должен подписывать запросы

2023-12-29 08:31 UTC, s-shpak commented on .gitignore
> +.golangci.yml
Почему ты добавил `.golangci.yml` в `.gitignore` ? Ты это не делал в предыдущес спринте?

2023-12-29 08:31 UTC, s-shpak commented on internal/agent/config/config.go
> +	workerPoolEnv, ok := os.LookupEnv("RATE_LIMIT")
Не стоит называть эту переменную `workerPoolEnv` (ткже как и поле объекта конфигурации) - это указывает не детали имплементации: если в будущем `worker pool` заменится на другой паттерн, нам надо будет изменять имена этих переменных

2023-12-29 08:31 UTC, s-shpak commented on internal/agent/config/config.go
> +			l.Error().Err(err).Msgf("strconv.Atoi, poll interval value: %s", pollIntervalEnv)
Зачем здесь логировать ошибку?

2023-12-29 08:31 UTC, s-shpak commented on internal/agent/integration/metric.go
> +				go func(req chan data, wgWrk *sync.WaitGroup) {
Почему на каждый тик ты создаешь `n` воркеров. Ты должен сделать следующее: при необходимости отправить что-то на сервер ты передаешь эту задачу в `worker pool`.

Например, если `RATE_LIMIT == 1`, то ты не сможешь отправить на сервер новые данные, пока не были отправлены предыдущие.

2023-12-29 08:31 UTC, s-shpak commented on internal/agent/integration/metric.go
> +					wgWrk.Done()
Лучше поместить это в `defer`

2023-12-29 08:31 UTC, s-shpak commented on internal/agent/service/metric.go
> +	wg.Done()
Что делает эта `wg` ? следит за тем, что горутина была запущена ? Зачем тебе это знать ?

2023-12-29 08:31 UTC, s-shpak commented on internal/agent/service/metric.go
> +		"TotalMemory":     <-memory,
Если ты везде пользуешься конкретными значениями, а не читаешь их из канала, то здесь я бы тоже получил эти величины синхронно

2023-12-29 08:31 UTC, s-shpak commented on internal/agent/service/metric.go
> +func getCPU(wg *sync.WaitGroup) <-chan int {
Если будешь оставлять подход с каналами, то придумай как сделать функцию, которую можно переиспользовать для `getCPU` и для `getMemory`

2023-12-29 08:31 UTC, s-shpak commented on internal/server/transport/rest/middleware/hmac.go
> +		h := r.Header.Get("Hash")
В задании требуется использовать `HashSHA256`

2023-12-29 08:31 UTC, s-shpak commented on internal/server/transport/rest/middleware/hmac.go
> +		data, _ := io.ReadAll(body)
Необходимо делать проверку на ошибки. Если берешь код из учебника, адаптируй его под свой use-case

2023-12-29 08:31 UTC, s-shpak commented on internal/server/transport/rest/middleware/hmac.go
> +		h1.Write(data)
Проверка

2024-01-09 15:41 UTC, 1Asi1 commented on .gitignore
> +.golangci.yml
убрал джобу и yml ибо не успевал поправить все замечания golangci

2024-01-09 15:48 UTC, 1Asi1 commented on internal/agent/service/metric.go
> +	wg.Done()
жду когда пулворкер отработает, потом идет отправка батчами

2024-01-09 16:07 UTC, 1Asi1 commented on internal/agent/integration/metric.go
> +				go func(req chan data, wgWrk *sync.WaitGroup) {
в моем представлении вроде так и происходит, каждый тик-> процесс выгрузки данных, делается пулл из воркеров в количестве рейт лимита, в канал записывается условно 30 задач и они читают из канала/отправляют в зависимости кто освободился. Если рейт== 1 , получается одна горутина и будет пыхтеть-читать/отправлять. Вроде пример паттерна идентичен из материала. Прошу подсказку, если ошибся, предыдущий коммент, не навел на мысль к сожалению(

2024-01-10 12:48 UTC, s-shpak commented on internal/agent/config/config.go
> +			l.Error().Err(err).Msgf("strconv.Atoi, poll interval value: %s", pollIntervalEnv)
Это не единсвтенное место, где логирование ошибок бессмысленно. Посмотри в том же файле, например

2024-01-10 12:54 UTC, s-shpak commented on internal/agent/integration/metric.go
> +				go func(req chan data, wgWrk *sync.WaitGroup) {
Это очень сложная логика, лучше сделать так:
1. ты можешь посылать метрики батчем, почему бы так и не делать
2. на новый тик ты забираешь батч метрик и передаешь их в канал, который читают воркеры. Если свободных воркеров нет, то можно либо заблокироваться, либо выкинуть ворнинг, дропнуть батч и ждать следующего тика.

Тебе не нужно будет использоать воркгруппы, создавать дополнительные го-рутины и т.п.

2024-01-10 13:09 UTC, s-shpak requested changes

2024-01-10 13:09 UTC, s-shpak commented on internal/agent/service/metric.go
> +	go func() {
Сейчас ты не выигрываешь ничего от использования го-рутин (скорее всего проигрывыаешь в эффективности). Сделай это просто синхронным. Если ты хочешь получать память и метрику cpu конкурентно, то это можно сделать через запск го-рутин в одной функции. Но я не уверен, что это даст какой-либо прирост по производительности

2024-01-10 13:09 UTC, s-shpak commented on internal/agent/integration/metric.go
> +							if err := c.sendToServerGauge(k, v); err != nil {
Необходимо добавить подпись запросов, отправляемых на сервер

2024-01-11 15:12 UTC, 1Asi1 commented on internal/agent/integration/metric.go
> +				go func(req chan data, wgWrk *sync.WaitGroup) {
Увидел что можно сделать конкретное количество воркеров перед циклом, а заполнять канал джобами в тикере. Надеюсь это то, что от меня требовалось, в ином случае прошу отредактировать как нужно было сделать, иначе так и не допру о чем речь, заранее спасибо

2024-01-11 15:55 UTC, s-shpak commented on internal/agent/integration/metric.go
> +				go func(req chan data, wgWrk *sync.WaitGroup) {
1. ты сначала отправляешь метрики по одной, а потом еще и батчем. Не делай так, отправляй только батчем
2. воркеры должны работать до завершения всего приложения. Они должны ожидать поступления новой задачи в канал и обрабатывать ее. Ты добьешься корректного рейт-лимитинга, т.к. ты оганичишь число воркеров. То есть план такой: создаешь канал задач -> запускаешь воркеров, которые в бесконечном цикле читают задачи из канала -> по тику пытаешься отправить батч метрик в канал задач -> если все ок, то продолжаешь выполнение; если записать не получается, дропаешь задачу, логируешь ошибку, продолжаешь выполнение.

Напиши в пачку, если остались вопросы по тому, что я имею в виду, пожалуйста

2024-01-11 15:55 UTC, s-shpak requested changes
См. комментарий к worker pool

2024-01-17 18:55 UTC, s-shpak approved these changes

2024-01-18 07:08 UTC, merged