Iter18
1Asi1/metric-track pull request #17
Opened 2024-02-28 11:58 UTC by 1Asi1

2024-02-29 17:25 UTC, s-shpak requested changes
1. Сейчас покрытие кода -- 13.6%, см. здесь как его можно расчитать: https://stackoverflow.com/questions/33444968/how-to-get-all-packages-code-coverage-together-in-go. Необходимо довести его до >= 40%
2. сейчас профили не содержат никаой информации. Чтобы сравнить потребление памяти, профилирование надо запустить на работающем приложении под нагрузкой. Например, можно запустить сервер и агент и написать небольшую утилиту, которая будет нагружать сервер запросами. Далее можно запустить профилирование на 5-10 секунд. Потом стоит попытаться найти место, которое можно оптимизировать и зарефаткорить его

2024-03-06 10:36 UTC, s-shpak requested changes
1. Текущее покрытие = 24.3%, необходимо >= 40%
2. При попытке выполнения команды `go tool pprof -top -diff_base=profiles/base.pprof profiles/result.pprof` получаю ошибку `Main binary filename not available.`. Думаю, что проблема в `profiles/result.pprof` -- он практически пустой

2024-03-06 13:59 UTC, 1Asi1 commented
go test ./... -cover показывает что самое минимальнео значение 41.8%

2024-03-12 09:26 UTC, 1Asi1 commented
гайд по ссылке тоже не дал 24.3%

2024-03-12 19:14 UTC, s-shpak requested changes
Привет! Вот архив с профилем (`profile.cov`), который я снял на своей машине. В `profile.cov.total` лежит результат выполнения `go tool cover -func profile.cov
`, который показывает покрытие в 26.4%. Посмотри, пожалуйста. ты получаешь другой профиль ? если да, то скинь его мне. Получиь профиль можно, если выполнить `go test -v -coverpkg=./... -coverprofile=profile.cov ./...`

[profile.zip](https://github.com/1Asi1/metric-track/files/14577508/profile.zip)

2024-03-17 10:01 UTC, s-shpak approved these changes

2024-03-18 06:57 UTC, merged