Iter5
1Asi1/metric-track pull request #5
Opened 2023-11-08 18:43 UTC by 1Asi1

2023-11-09 20:32 UTC, s-shpak requested changes
Необходимо также исправить код, чтобы прошли автотесты

2023-11-09 20:32 UTC, s-shpak commented on cmd/agent/main.go
> +		fmt.Println(err)
Если произошла ошибка, то процесс надо завершить. Для этого в `main` можно использовать `log.Fatal`

2023-11-09 20:32 UTC, s-shpak commented on cmd/server/main.go
> +		fmt.Println(err)
См. коммент к коду агента

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +type Client interface {
Тебе не нужен этот интерфейс

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +func New(cfg config.Config, s service.Service) Client {
Из функций надо возвращать структуры (или указатели на них), а не интерфейсы

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +	HTTP    *resty.Client
Зачем делать это поле экспортируемым ?

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +	for i := 1; ; i++ {
Принимать решение о сборе метрик надо не через "циклы", а с помощью `time.Ticker`

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +	var res service.Metric
Зачем ты объявляешь переменные здесь, а не там, где они используются?

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +			fmt.Printf("stat:  [value: %+v | count: %+v]\n", res.RandomValue, res.PollCount)
Если ты хочешь что-то залогировать здесь, то используй `log`. Но, вообще говоря, здесь логирование не требуется, потому лучше убрать из PR

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +				fmt.Println(err)
Если произошла ошибка, то можно залогировать и вызвать `continue`, чтобы начать новый цикл

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +	err = res.RawBody().Close()
Закрывать значение лучше в `defer`, сразу после проверки ошибки на строке 85 (если ошибки нет, конечно)

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +		return errors.New("status not ok")
Стоит добавить, какой статус получен

2023-11-09 20:32 UTC, s-shpak commented on internal/agent/integration/metric.go
> +	url := fmt.Sprintf("http://%s/update/%s/%s/%f", c.cfg.MetricServerAddr, s.Gauge, "Name", data.RandomValue)
А как отправляются остальные метрики?

2023-11-09 20:32 UTC, s-shpak commented on internal/config/config.go
> +func parseFlag() {
Чтобы получить значения необходимо вызвать `flag.Parse` после "регистрации" всех флагов

2023-11-09 20:32 UTC, s-shpak commented on internal/config/config.go
> +var hostFlag string
Глобальные переменные не нужны

2023-11-09 20:32 UTC, s-shpak commented on internal/config/config.go
> +	pollInterval := os.Getenv("")
Лучше использовать `os.LookupEnv`, т.к. пустое и незаданное значения могут иметь разный смысл

2023-11-09 20:32 UTC, s-shpak commented on internal/config/config.go
> +	PollInterval     int
Лучше чтобы интервалы сразу были представлены как `time.Duration`

2023-11-09 20:32 UTC, s-shpak commented on internal/server/apiserver/apiserver.go
> +	Mux *chi.Mux
Зачем экспортировать это поле?

2023-11-09 20:32 UTC, s-shpak commented on internal/server/apiserver/apiserver.go
> +		log.Panicf("http.ListenAndServe panic: %v", err)
Паниковать в глубине кода, как и в любой другой части этого проекта, нельзя. Прокидывай ошибку наверх, там логируй ее и завершай процесс при помощи `log.Fatal`

2023-11-09 20:32 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +func New(path string) Store {
Зачем передавать сюда `path`?

2023-11-09 20:32 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +type Store interface {
Этот интерфейс:
1. Пока не нужен
2. В будущем, когда у нас будет несколько имплементаций, должен быть помещен там, где он используется

2023-11-09 20:32 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +func (m memoryStore) Get(ctx context.Context) (map[string]Type, error) {
Логичнее было бы передать имя метрики сюда и вернуть только запрашиваемую метрику, а не весь стор

2023-11-09 20:32 UTC, s-shpak commented on internal/server/service/metric.go
> +		return "", ErrNotFound
В ошибке стоит указывать, какая именно метрика не найдена

2023-11-09 20:32 UTC, s-shpak commented on internal/server/service/metric.go
> +	return fmt.Sprintf("%d", data[name].Counter), nil
Здесь тоже стоит использовать `strconv`

2023-11-09 20:32 UTC, s-shpak commented on internal/server/service/metric_test.go
> +//type storeTest interface {
deadcode

2023-11-10 08:47 UTC, 1Asi1 commented
по поводу "исправить тесты" я честно говоря не имею понимания почему они падают, с ошибкой "Не удалось дождаться пока на порт 43943 начнут поступать данные: context deadline exceeded", локально те-же команды работают

2023-11-10 13:45 UTC, 1Asi1 commented on internal/agent/integration/metric.go
> +	var res service.Metric
что имеется ввиду? сейчас эта переменная за областью видимости цикла чтобы обновлять значение перед отправкой

2023-11-10 14:07 UTC, 1Asi1 commented on internal/agent/integration/metric.go
> +	url := fmt.Sprintf("http://%s/update/%s/%s/%f", c.cfg.MetricServerAddr, s.Gauge, "Name", data.RandomValue)
я честно говоря так и не понял, в инкременте 2 только поднимался вопрос об остальных метриках,а как их отправлять если ручки заточены под Guage и Counter. В Header? 
<img width="375" alt="Снимок экрана 2023-11-10 в 17 05 24" src="https://github.com/1Asi1/metric-track/assets/84197759/d8749ffa-b08c-4d14-9056-a47254d201e8">

2023-11-13 13:46 UTC, s-shpak requested changes

2023-11-13 13:46 UTC, s-shpak commented on internal/agent/integration/metric.go
> +		return fmt.Errorf("error: %w status: %d", errors.New("status not ok"), res.StatusCode())
кажется, что нет смысла испоьзовать здесь `errors.New`. Может как-то так:

```suggestion
		return fmt.Errorf("expected status %d, got: %d", http.StatusOK, res.StatusCode())
```

2023-11-13 13:46 UTC, s-shpak commented on internal/agent/service/metric.go
> +type Service interface {
Зачем этот интерфейс?

2023-11-13 13:46 UTC, s-shpak commented on internal/server/service/metric.go
> +type Service interface {
Зачем этот интерфейс ?

2023-11-13 13:46 UTC, s-shpak commented on internal/server/transport/rest/v1/metric_test.go
> +type store struct {
А зачем мокать стор? Почему бы не использовать текущую in-memory имплементацию?

2023-11-15 20:56 UTC, s-shpak approved these changes

2023-11-16 16:14 UTC, merged