Iter9
1Asi1/metric-track pull request #9
Opened 2023-11-28 13:10 UTC by 1Asi1

2023-11-30 12:19 UTC, s-shpak requested changes
Добавь `golangci-lint` локально и в `github actions`. Здесь описано как: https://github.com/s-shpak/praktikum-golangci-lint

2023-11-30 12:19 UTC, s-shpak commented on cmd/agent/main.go
> +	out := zerolog.ConsoleWriter{
Лучше спрятать конфигурацию логера в отдельную функцию

2023-11-30 12:19 UTC, s-shpak commented on cmd/agent/main.go
> +	cfg, err := config.New(l)
Обычно конфигурация парсится перед логгером, т.к. там может быть указание на уровень логирования. Ошибка, в этом случае, логируется каким-нибудь дефолтным логгером (можно и `log`)

2023-11-30 12:19 UTC, s-shpak commented on cmd/server/main.go
> +		l.Fatal().Err(err).Msg("http.ListenAndServe")
А ошибка точно придет от `http.ListenAndServe`?

2023-11-30 12:19 UTC, s-shpak commented on cmd/server/main.go
> +	out := zerolog.ConsoleWriter{
Соответственно, при определении специальной функции, ее можно вызывать и для кода сервера, и для кода агента

2023-11-30 12:19 UTC, s-shpak commented on internal/agent/integration/metric.go
> +		l.Error().Err(err).Msgf("expected status %d, got: %d", http.StatusOK, res.StatusCode())
Зачем логировать ошибку здесь, если ты пробрасываешь ее наверх ?

2023-11-30 12:19 UTC, s-shpak commented on internal/agent/service/metric_test.go
> +func newLogger() zerolog.Logger {
Эта фнкция потенциално не нужна

2023-11-30 12:19 UTC, s-shpak commented on internal/server/apiserver/apiserver.go
> +	memoryStore := memory.New(s.log, s.cfg)
Странно, что для инициализации `store` требуется весь объект конфигурации. Наверное, лучше разбить его на несколько составляющих

2023-11-30 12:19 UTC, s-shpak commented on internal/server/repository/memory/store.go
>  type Store struct {
Я посоветовал бы тебе создать два разных типа `in-memory store` и `file store`, где `file store` будет просто оборачивать `in-memory store`

2023-11-30 12:19 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +		l.Error().Err(ErrNotFound).Msgf("m.metric[name], name: %s", name)
Если ошибка пробрасывается наверх, то нет смысла ее логировать

2023-11-30 12:19 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +		return service.Type{}, ErrNotFound
```suggestion
		return service.Type{}, fmt.Errorf("problem with m.metric[%s]: %w", name, ErrNotFound)
```

2023-11-30 12:19 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +			default:
С default ты не засыпаешь до следующего интервала, а сразу переходишь к новому циклу. default можно полностью заменить на `for range ticker.C`

2023-11-30 12:19 UTC, s-shpak commented on internal/server/service/metric_test.go
> +func (s storeTest) Get(ctx context.Context) (map[string]Type, error) {
Не ясно, зачем ты мокаешь это

2023-11-30 12:19 UTC, s-shpak commented on internal/server/transport/rest/middleware/compress.go
> +func GzipMiddleware(next http.HandlerFunc) http.HandlerFunc {
А если прилетит сжатый запрос?

2023-11-30 12:19 UTC, s-shpak commented on internal/server/transport/rest/v1/v1.go
>  	h.handler.Mux.Route("/", func(r chi.Router) {
1. Не реализован logging middleware
2. Для регистрации middleware лучше использовать `r.Use()`

2023-11-30 12:19 UTC, s-shpak commented on internal/server/transport/rest/v1/metric.go
> +	l.Info().Msgf("req body: %s", data)
Не стоит логировать такие вещи на `Info` уровне, это забьет лог. Лучше не логировать вообще, либо использовать уровень `Debug`

2023-12-04 08:15 UTC, 1Asi1 commented on internal/server/service/metric_test.go
> +func (s storeTest) Get(ctx context.Context) (map[string]Type, error) {
чтобы не писать в файл, если и удалить то тест не запустится из-за циклического импорта store и service

2023-12-05 11:45 UTC, s-shpak commented on internal/server/service/metric_test.go
> +func (s storeTest) Get(ctx context.Context) (map[string]Type, error) {
1. Тебе стоит использовать `in-memory store` реализацию в качестве мока - это, по сути, то же самое. Либо генерировать собственные моки. Но определять новую структуру для тестов не имеет смысла - это лишний код.
2. Проблема с циклической зависимостью говорит о том, что твой проект неправильно структурирован. Ошибка в данном случае в том, что твой `store` импортиурет пакет `service`, хотя по принципу направления зависимостей нижние уровни не могут зависеть от верхних. Даже если бы ты не соблюдал этот принцип (его несоблюдение скорее всего со временем превратит код в спагетти), то циклической зависимости надо избегать. Например, вынести код, от которого зависит `store` в отдельный пакет на уровне `service`.
Но в данном случае я рекомендую тебе вообще отказаться от этой зависимости. Подумай как

2023-12-05 11:52 UTC, s-shpak requested changes
1. Не резолвь комментарии сам, пожалуйста, - мне проще, если я сам буду их разрешать. Если ты хочешь помечать комментарии, которые ты уже поправил, используй, например, emoji
2. В GitHub Actions необходимо добавить линтер, как описано здесь: https://github.com/s-shpak/praktikum-golangci-lint#настройка-github-actions

2023-12-05 11:52 UTC, s-shpak commented on internal/server/repository/memory/store.go
> +type FileStore struct {
Сейчас `MemoryStore` и `FileStore` организованы очень сложно. Например, очень сложно понять как именно происходит выбор файла, куда производится запись. А если это сложно понять, значит поддерживать это тоже будет непросто.

Здесь я объснял, как лучше это сделать: https://app.pachca.com/chats/7545460?message=104649294

2023-12-06 18:01 UTC, s-shpak approved these changes

2023-12-07 06:40 UTC, merged